name: release-version

runs:
  using: 'composite'
  steps:
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        name: Bonzomatic Network  ${{ github.ref_name }}
        files: |
          Release_1.txt
          Release_2.txt