name: Tag Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: windows-2019
    env:
      NDI_SDK_DIR: c:/Program Files/NewTek/NDI 4 SDK/
    steps:
    - uses: actions/checkout@v3
    - name: Download and install NDI SDK
      run: "echo test >> ~/test.txt"
    - name: Download and install NDI SDK
      run: "dir ~/"
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: ~/test.txt