name: Tag Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: windows-2019
    env:
      NDI_SDK_DIR: c:/Program Files/NewTek/NDI 4 SDK/
    steps:
    - name: Get date
      id: date
      run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
    - name: Download and install NDI SDK
      run: "echo test >> ~/test.txt"
    - name: Download and install NDI SDK
      run: "ls -alih"
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: ~/test.txt